services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.Dockerfile
    image: ${DOCKER_USERNAME}/${COMPOSE_PROJECT_NAME}:nginx-${COMMIT_TAG}
    networks:
      - web_network
      - traefik_net
    volumes:
      - scripts_data:/var/www/frontend/web/js/dist
      - backend_assets_data:/var/www/backend/web/assets
      - frontend_assets_data:/var/www/frontend/web/assets
      - uploads_data:/var/www/common/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      # HTTP Router (port 80) - redirect to HTTPS
      - "traefik.http.routers.humblegallery-web.rule=Host(`humblegallery.ru`) || Host(`www.humblegallery.ru`) || Host(`admin.humblegallery.ru`) || Host(`www.admin.humblegallery.ru`)"
      - "traefik.http.routers.humblegallery-web.entrypoints=web"
      - "traefik.http.routers.humblegallery-web.middlewares=redirect-to-https@file"

      # HTTPS Router (port 443) - serve TLS
      - "traefik.http.routers.humblegallery-secure.rule=Host(`humblegallery.ru`) || Host(`www.humblegallery.ru`) || Host(`admin.humblegallery.ru`) || Host(`www.admin.humblegallery.ru`)"
      - "traefik.http.routers.humblegallery-secure.entrypoints=websecure"
      - "traefik.http.routers.humblegallery-secure.tls.certresolver=myresolver"
    depends_on:
      - app

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ./
      dockerfile: ./docker/php/prod.Dockerfile
    image: ${DOCKER_USERNAME}/${COMPOSE_PROJECT_NAME}:app-${COMMIT_TAG}
    volumes:
      - scripts_data:/var/www/frontend/web/js/dist
      - backend_assets_data:/var/www/backend/web/assets
      - frontend_assets_data:/var/www/frontend/web/assets
      - uploads_data:/var/www/common/uploads
    env_file:
      - .env
    networks:
      - db_network
      - web_network
    depends_on:
      - mysql

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:8.0.0
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
    mem_limit: 512m

networks:
  web_network:
  db_network:
    internal: true
  traefik_net:
    external: true
volumes:
  mysql_data:
  uploads_data:
  scripts_data:
  backend_assets_data:
  frontend_assets_data: