version: '3.2'

services:

  # NGINX
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/${COMPOSE_PROJECT_DIR}
      - ./docker/nginx:/etc/nginx/conf.d/
      # - ${APP_STORAGE_PATH}:/mnt/storage
    environment:
      NGINX_PORT: 8080
    networks:
      - humblegallery-network


  #FPM
  fpm:
    container_name: ${COMPOSE_PROJECT_NAME}-fpm
    build:
      # Путь до директории с Dockerfile
      context: ./docker/php
      # Маппинг томов
    volumes:
      - .:/var/www/${COMPOSE_PROJECT_DIR}
    networks:
      - humblegallery-network


  #MYSQL
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${APP_STORAGE_PATH}:/var/lib/mysql
    networks:
      - humblegallery-network

networks:
  humblegallery-network:
    driver: bridge