services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:1.27.3-alpine
    networks:
      - web
    ports:
      - ${FRONTEND_PORT}:80
      - ${BACKEND_PORT}:88
    volumes:
      - uploads_data:/var/www/common/uploads
      - ./docker/nginx/prod:/etc/nginx/conf.d/

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ./
      dockerfile: ./docker/php/prod.Dockerfile
    volumes:
      - uploads_data:/var/www/common/uploads
    env_file:
      - .env
    networks:
      - internal
      - web
    depends_on:
      - mysql

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:9.2.0
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    internal: true
  web:
volumes:
  db-data:
  uploads_data: