services:
  # NGINX
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
#    restart: always
    networks:
      - web
    ports:
      - ${FRONTEND_PORT}:80
      - ${BACKEND_PORT}:88
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/

  # FPM
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - internal
      - web
    depends_on:
      - mysql


  # MYSQL
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: mysql:latest
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ${COMPOSE_PROJECT_NAME}-mysql-data:/var/lib/mysql
    networks:
      - internal

networks:
  internal:
    internal: true
  web:
volumes:
  db-data:
    name: ${COMPOSE_PROJECT_NAME}-mysql-data
