name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    # триггер для запуска workflow при пуше тегов, соответствующих шаблону
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.dist', '.env');"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.ref_name }}

    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Deploy to Production Server
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USER }}
            key: ${{ secrets.SERVER_SSH_KEY }}
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.ref_name }}
              docker-compose -f docker-compose.prod.yml up -d